<a href="https://colab.research.google.com/github/ham-codes7/Exploratory-Data-Analysis-/blob/main/25BDS0067_Lab_21_07_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
python1 = pd.DataFrame({
    'StudentID':[101,103,105,107,109],
    'PythonScore':[85,76,90,65,88]
})

python2 = pd.DataFrame({
    'StudentID':[102,104,106,108,110],
    'PythonScore':[70,82,75,91,68]
})

datascience1 = pd.DataFrame({
    'StudentID':[101,102,103,105,107],
    'DSScore':[78,81,74,89,92]
})

datascience2 = pd.DataFrame({
    'StudentID':[104,106,108,109],
    'DSScore':[85,76,83,90]
})

In [ ]:
python = pd.concat([python1, python2], ignore_index=True)

datascience = pd.concat([datascience1, datascience2], ignore_index=True)

python

   StudentID  PythonScore
0        101           85
1        103           76
2        105           90
3        107           65
4        109           88
5        102           70
6        104           82
7        106           75
8        108           91
9        110           68

In [ ]:
datascience

   StudentID  DSScore
0        101       78
1        102       81
2        103       74
3        105       89
4        107       92
5        104       85
6        106       76
7        108       83
8        109       90

In [ ]:
combined = pd.concat([python, datascience], axis=1)

combined

   StudentID  PythonScore  StudentID  DSScore
0        101           85      101.0     78.0
1        103           76      102.0     81.0
2        105           90      103.0     74.0
3        107           65      105.0     89.0
4        109           88      107.0     92.0
5        102           70      104.0     85.0
6        104           82      106.0     76.0
7        106           75      108.0     83.0
8        108           91      109.0     90.0
9        110           68        NaN      NaN

In [ ]:
inner = python.merge(datascience, how='inner')

inner

   StudentID  PythonScore  DSScore
0        101           85       78
1        103           76       74
2        105           90       89
3        107           65       92
4        109           88       90
5        102           70       81
6        104           82       85
7        106           75       76
8        108           91       83

In [ ]:
left = python.merge(datascience, how='left')

left

   StudentID  PythonScore  DSScore
0        101           85     78.0
1        103           76     74.0
2        105           90     89.0
3        107           65     92.0
4        109           88     90.0
5        102           70     81.0
6        104           82     85.0
7        106           75     76.0
8        108           91     83.0
9        110           68      NaN

In [ ]:
right = python.merge(datascience, how='right')

right

   StudentID  PythonScore  DSScore
0        101           85       78
1        102           70       81
2        103           76       74
3        105           90       89
4        107           65       92
5        104           82       85
6        106           75       76
7        108           91       83
8        109           88       90

In [ ]:
sales = pd.DataFrame({
    'Company':['Apple','Samsung','Sony','Dell','HP'],
    'Product':['Phone','Tablet','TV','Laptop','Printer'],
    'Quantity':[5,8,3,6,4],
    'UnitPrice':[70000,25000,45000,80000,12000]
})

sales

   Company  Product  Quantity  UnitPrice
0    Apple    Phone         5      70000
1  Samsung   Tablet         8      25000
2     Sony       TV         3      45000
3     Dell   Laptop         6      80000
4       HP  Printer         4      12000

In [ ]:
sales['TotalPrice'] = sales['Quantity'] * sales['UnitPrice']

sales

   Company  Product  Quantity  UnitPrice  TotalPrice
0    Apple    Phone         5      70000      350000
1  Samsung   Tablet         8      25000      200000
2     Sony       TV         3      45000      135000
3     Dell   Laptop         6      80000      480000
4       HP  Printer         4      12000       48000

In [ ]:
sales['Company'].value_counts()

Company
Apple      1
Samsung    1
Sony       1
Dell       1
HP         1
Name: count, dtype: int64

In [ ]:
sales['Company'].value_counts()

Company
Apple      1
Samsung    1
Sony       1
Dell       1
HP         1
Name: count, dtype: int64

In [ ]:
sales = pd.DataFrame({
    'Company':['Apple','Apple','Samsung','Samsung','Sony','Sony','Dell'],
    'Quantity':[2,4,3,1,5,2,6],
    'UnitPrice':[70000,70000,25000,25000,45000,45000,80000]
})

In [ ]:
sales['Company'].value_counts()

Company
Apple      2
Samsung    2
Sony       2
Dell       1
Name: count, dtype: int64

In [ ]:
sales.describe()

       Quantity     UnitPrice
count  7.000000      7.000000
mean   3.285714  51428.571429
std    1.799471  22307.376529
min    1.000000  25000.000000
25%    2.000000  35000.000000
50%    3.000000  45000.000000
75%    4.500000  70000.000000
max    6.000000  80000.000000

In [ ]:
data = np.arange(15).reshape((3,5))

indexers = ['Temperature','Humidity','Rainfall']

weather = pd.DataFrame(
    data,
    index=indexers,
    columns=['Delhi','Mumbai','Chennai','Bangalore','Hyderabad']
)

weather

             Delhi  Mumbai  Chennai  Bangalore  Hyderabad
Temperature      0       1        2          3          4
Humidity         5       6        7          8          9
Rainfall        10      11       12         13         14

In [ ]:
stacked = weather.stack()

stacked

Temperature  Delhi         0
             Mumbai        1
             Chennai       2
             Bangalore     3
             Hyderabad     4
Humidity     Delhi         5
             Mumbai        6
             Chennai       7
             Bangalore     8
             Hyderabad     9
Rainfall     Delhi        10
             Mumbai       11
             Chennai      12
             Bangalore    13
             Hyderabad    14
dtype: int64

In [ ]:
stacked.unstack()

             Delhi  Mumbai  Chennai  Bangalore  Hyderabad
Temperature      0       1        2          3          4
Humidity         5       6        7          8          9
Rainfall        10      11       12         13         14

In [ ]:
series1 = pd.Series(
    [100,200,300],
    index=['Math','Physics','Chemistry']
)

series2 = pd.Series(
    [400,500],
    index=['Biology','English']
)

In [ ]:
frame = pd.concat([series1, series2], keys=['Semester1','Semester2'])

frame

Semester1  Math         100
           Physics      200
           Chemistry    300
Semester2  Biology      400
           English      500
dtype: int64

In [ ]:
frame.unstack()

           Biology  Chemistry  English   Math  Physics
Semester1      NaN      300.0      NaN  100.0    200.0
Semester2    400.0        NaN    500.0    NaN      NaN