<a href="https://colab.research.google.com/github/ham-codes7/Exploratory-Data-Analysis-/blob/main/Exp4_28.07.26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Handling Missing Data

This section demonstrates various ways to handle missing values (NaN) in pandas DataFrames.

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd

### Creating an initial DataFrame

Let's assume we have a DataFrame as shown.

In [2]:
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
display(dfx)

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

### Adding missing values to the DataFrame

We'll introduce `NaN` values to demonstrate missing data handling.

In [3]:
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx['store4']['apple'] = 20.
display(dfx)

/tmp/ipykernel_754/3073848240.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['apple'] = 20.

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

### Checking for NaN values in pandas objects

We can use `isnull()`, `notnull()`, `sum()`, and `count()` methods to inspect missing values.

In [4]:
# 1. Check the following example:
display(dfx.isnull())

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [5]:
# 2. Check it out in action:
display(dfx.notnull())

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [6]:
# 3. We can use the sum() method to count the number of NaN values in each store.
display(dfx.isnull().sum())

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [7]:
# 4. We can go one level deeper to find the total number of missing values
display(dfx.isnull().sum().sum())

np.int64(15)

In [8]:
# 5. So, instead of counting the number of missing values, we can count the number of reported values:
display(dfx.count())

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

### Dropping missing values

One way to handle missing values is to remove them from our dataset using `dropna()`.

In [9]:
# Display non-null values in 'store4'
display(dfx.store4[dfx.store4.notnull()])

# Drop NaN values from 'store4'
display(dfx.store4.dropna())

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

In [10]:
# If dropna() is applied to the entire dataframe, then it will drop all rows with at least one NaN value.
display(dfx.dropna())

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

#### Dropping by rows

We can drop rows that have entirely NaN values using `how='all'`.

In [11]:
display(dfx.dropna(how='all'))

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

#### Dropping by columns

We can also pass `axis=1` to check for NaNs by columns, and `thresh` to specify a minimum number of non-NaN values required.

In [12]:
# Drop columns where all values are NaN
display(dfx.dropna(how='all', axis=1))

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN

In [13]:
# Drop columns that have less than 5 non-NaN values
display(dfx.dropna(thresh=5, axis=1))

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
watermelon    15.0    16.0    17.0
oranges        NaN     NaN     NaN

### Mathematical operations with NaN

NaN values can affect mathematical operations like mean, sum, and cumulative sum.

In [17]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
print(f"Numpy array mean: {ar1.mean()}, Pandas Series mean: {ser1.mean()}")

Numpy array mean: nan, Pandas Series mean: 200.0

In [18]:
# Let's compute the total quantity of fruits sold by store4:
ser2 = dfx.store4
print(f"Sum of store4: {ser2.sum()}")

Sum of store4: 38.0

In [19]:
# Average
print(f"Average of store4: {ser2.mean()}")

Average of store4: 19.0

In [20]:
# Cumulative Summing
display(ser2.cumsum())

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

### Filling missing values

We can use the `fillna()` method to replace NaN values with specified values or using interpolation methods like forward-fill (`ffill`) or backward-fill (`bfill`).

In [21]:
# Fill NaN values with 0
filledDf = dfx.fillna(0)
display(filledDf)

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [22]:
# Check the difference in mean between NaN and 0-filled DataFrames
print("Original DataFrame mean (excluding NaN):")
display(dfx.mean())
print("Filled DataFrame mean (NaN replaced with 0):")
display(filledDf.mean())

Original DataFrame mean (excluding NaN):

store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64

Filled DataFrame mean (NaN replaced with 0):

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

#### Backward and forward filling

In [23]:
# Forward-filling (method = 'ffill')
display(dfx.store4.fillna(method='ffill'))

/tmp/ipykernel_754/580291976.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(dfx.store4.fillna(method='ffill'))

apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64

In [24]:
# Backward-filling (method = 'bfill')
display(dfx.store4.fillna(method='bfill'))

/tmp/ipykernel_754/1008535419.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(dfx.store4.fillna(method='bfill'))

apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

## Advanced Missing Value Imputation with scikit-learn

This section demonstrates various imputation techniques for handling missing values using `sklearn`.

In [32]:

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
# numpy and pandas are already imported in previous cells

### Create a sample DataFrame with missing values

In [26]:
# Create sample DataFrame with missing values (NaN)
df = pd.DataFrame(
    {
        "Age": [25, np.nan, 30, 45, 22],
        "Salary": [50000, 60000, np.nan, 80000, 45000],
        "Category": ["A", "B", "A", np.nan, "B"],
    }
)
display(df)

    Age   Salary Category
0  25.0  50000.0        A
1   NaN  60000.0        B
2  30.0      NaN        A
3  45.0  80000.0      NaN
4  22.0  45000.0        B

### 1. Mean Imputation (for Numerical Features)

This method replaces missing numerical values with the mean of the column.

In [27]:
# 1. Mean Imputation (Numerical)
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
display(df)

    Age   Salary Category  Age_Mean
0  25.0  50000.0        A      25.0
1   NaN  60000.0        B      30.5
2  30.0      NaN        A      30.0
3  45.0  80000.0      NaN      45.0
4  22.0  45000.0        B      22.0

### 2. Median Imputation (for Numerical Features)

Median imputation is robust to outliers and replaces missing numerical values with the median of the column.

In [28]:
# 2. Median Imputation (Numerical - robust to outliers)
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])
display(df)

    Age   Salary Category  Age_Mean  Salary_Median
0  25.0  50000.0        A      25.0        50000.0
1   NaN  60000.0        B      30.5        60000.0
2  30.0      NaN        A      30.0        55000.0
3  45.0  80000.0      NaN      45.0        80000.0
4  22.0  45000.0        B      22.0        45000.0

### 3. Mode Imputation (for Categorical Features)

Mode imputation replaces missing categorical values with the most frequent value in the column.

In [30]:
# 3. Mode Imputation (Categorical - most frequent)
mode_imputer = SimpleImputer(strategy="most_frequent")
# The fit_transform method returns a 2D array, which causes an error when assigning to a single column.
# We need to flatten it to a 1D array.
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
display(df)

    Age   Salary Category  Age_Mean  Salary_Median Category_Mode
0  25.0  50000.0        A      25.0        50000.0             A
1   NaN  60000.0        B      30.5        60000.0             B
2  30.0      NaN        A      30.0        55000.0             A
3  45.0  80000.0      NaN      45.0        80000.0             A
4  22.0  45000.0        B      22.0        45000.0             B

### 4. MICE Imputation (Multivariate Imputation by Chained Equations)

MICE is an advanced method that models each feature with missing values as a function of other features, and then imputes the missing values sequentially.

In [31]:
# 4. MICE Imputation (Multivariate Imputation by Chained Equations)
# Select numerical columns for MICE
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
display(df)

,Age,Salary,Category,Age_Mean,Salary_Median,Category_Mode,Age_MICE,Salary_MICE
0,25.0,50000.0,A,25.0,50000.0,A,25.000000,50000.000000
1,NaN,60000.0,B,30.5,60000.0,B,31.766487,60000.000000
2,30.0,NaN,A,30.0,55000.0,A,30.000000,57324.583367
3,45.0,80000.0,NaN,45.0,80000.0,A,45.000000,80000.000000
4,22.0,45000.0,B,22.0,45000.0,B,22.000000,45000.000000