<a href="https://colab.research.google.com/github/ham-codes7/Exploratory-Data-Analysis-/blob/main/Tutorial_q_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving employee_salary.csv to employee_salary.csv

In [ ]:
df = pd.read_csv("employee_salary.csv")

In [ ]:
df.head()

   EmployeeID   Name Department  Age  Experience  Salary  Gender       City
0         101   John         HR   28           3   45000    Male    Chennai
1         102  Priya         IT   30           5   60000  Female  Bangalore
2         103  Rahul    Finance   35           8   75000    Male  Hyderabad
3         104  Sneha  Marketing   27           2   42000  Female     Mumbai
4         105  Arjun         IT   32           6   68000    Male    Chennai

In [ ]:
df.tail()

   EmployeeID    Name Department  Age  Experience  Salary  Gender       City
5         106   Kavya         HR   29           4   50000  Female      Delhi
6         107  Vikram      Sales   38          10   85000    Male       Pune
7         108    Neha    Finance   31           7   72000  Female  Bangalore
8         109   Kiran         IT   26           2   48000    Male  Hyderabad
9         110   Meera  Marketing   34           9   78000  Female    Chennai

In [ ]:
df.shape

(10, 8)

In [ ]:
rows, columns = df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 10
Number of columns: 8

In [ ]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Experience', 'Salary',
       'Gender', 'City'],
      dtype='object')

In [ ]:
print(df.columns)

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Experience', 'Salary',
       'Gender', 'City'],
      dtype='object')

In [ ]:
for column in df.columns:
    print(column)

EmployeeID
Name
Department
Age
Experience
Salary
Gender
City

In [ ]:
df.dtypes

EmployeeID     int64
Name          object
Department    object
Age            int64
Experience     int64
Salary         int64
Gender        object
City          object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  10 non-null     int64
 1   Name        10 non-null     object
 2   Department  10 non-null     object
 3   Age         10 non-null     int64
 4   Experience  10 non-null     int64
 5   Salary      10 non-null     int64
 6   Gender      10 non-null     object
 7   City        10 non-null     object
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

In [ ]:
df.describe()

       EmployeeID        Age  Experience        Salary
count    10.00000  10.000000   10.000000     10.000000
mean    105.50000  31.000000    5.600000  62300.000000
std       3.02765   3.800585    2.875181  15355.418877
min     101.00000  26.000000    2.000000  42000.000000
25%     103.25000  28.250000    3.250000  48500.000000
50%     105.50000  30.500000    5.500000  64000.000000
75%     107.75000  33.500000    7.750000  74250.000000
max     110.00000  38.000000   10.000000  85000.000000

In [ ]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Age           0
Experience    0
Salary        0
Gender        0
City          0
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

EmployeeID    0.0
Name          0.0
Department    0.0
Age           0.0
Experience    0.0
Salary        0.0
Gender        0.0
City          0.0
dtype: float64

In [ ]:
print("Column with the highest missing values:")
print(df.isnull().sum().idxmax())

print("Number of missing values:")
print(df.isnull().sum().max())

Column with the highest missing values:
EmployeeID
Number of missing values:
0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

EmployeeID    0
Name          0
Department    0
Age           0
Experience    0
Salary        0
Gender        0
City          0
dtype: int64

In [ ]:
duplicates = df.duplicated().sum()
print("Number of Duplicate Records:", duplicates)

Number of Duplicate Records: 0

In [ ]:
print("Dataset Size Before Cleaning:", len(df))

Dataset Size Before Cleaning: 10

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Dataset Size After Cleaning:", len(df))

Dataset Size After Cleaning: 10

In [ ]:
df = df.dropna()

In [ ]:
df["Salary"].fillna(df["Salary"].mean(), inplace=True)

/tmp/ipykernel_2824/2346652894.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("employee_salary.csv")

# Display first and last 5 records
print(df.head())
print(df.tail())

# Dataset shape
rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

# Metadata
print(df.columns)
print(df.dtypes)
df.info()

# Descriptive statistics
print(df.describe())

# Missing values
print(df.isnull().sum())

missing_percentage = (df.isnull().sum() / len(df)) * 100
print("\nPercentage of Missing Values:")
print(missing_percentage)

print("\nColumn with Highest Missing Values:")
print(df.isnull().sum().idxmax())

print("Missing Value Count:")
print(df.isnull().sum().max())

# Duplicate records
duplicates = df.duplicated().sum()
print("Number of Duplicate Records:", duplicates)

# Dataset size before cleaning
print("Dataset Size Before Cleaning:", len(df))

# Remove duplicates
df = df.drop_duplicates()

# Dataset size after cleaning
print("Dataset Size After Cleaning:", len(df))

   EmployeeID   Name Department  Age  Experience  Salary  Gender       City
0         101   John         HR   28           3   45000    Male    Chennai
1         102  Priya         IT   30           5   60000  Female  Bangalore
2         103  Rahul    Finance   35           8   75000    Male  Hyderabad
3         104  Sneha  Marketing   27           2   42000  Female     Mumbai
4         105  Arjun         IT   32           6   68000    Male    Chennai
   EmployeeID    Name Department  Age  Experience  Salary  Gender       City
5         106   Kavya         HR   29           4   50000  Female      Delhi
6         107  Vikram      Sales   38          10   85000    Male       Pune
7         108    Neha    Finance   31           7   72000  Female  Bangalore
8         109   Kiran         IT   26           2   48000    Male  Hyderabad
9         110   Meera  Marketing   34           9   78000  Female    Chennai
Number of rows: 10
Number of columns: 8
Index(['EmployeeID', 'Name', 'Department', 'Age', 'Experience', 'Salary',
       'Gender', 'City'],
      dtype='object')
EmployeeID     int64
Name          object
Department    object
Age            int64
Experience     int64
Salary         int64
Gender        object
City          object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  10 non-null     int64
 1   Name        10 non-null     object
 2   Department  10 non-null     object
 3   Age         10 non-null     int64
 4   Experience  10 non-null     int64
 5   Salary      10 non-null     int64
 6   Gender      10 non-null     object
 7   City        10 non-null     object
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes
       EmployeeID        Age  Experience        Salary
count    10.00000  10.000000   10.000000     10.000000
mean    105.50000  31.000000    5.600000  62300.000000
std       3.02765   3.800585    2.875181  15355.418877
min     101.00000  26.000000    2.000000  42000.000000
25%     103.25000  28.250000    3.250000  48500.000000
50%     105.50000  30.500000    5.500000  64000.000000
75%     107.75000  33.500000    7.750000  74250.000000
max     110.00000  38.000000   10.000000  85000.000000
EmployeeID    0
Name          0
Department    0
Age           0
Experience    0
Salary        0
Gender        0
City          0
dtype: int64

Percentage of Missing Values:
EmployeeID    0.0
Name          0.0
Department    0.0
Age           0.0
Experience    0.0
Salary        0.0
Gender        0.0
City          0.0
dtype: float64

Column with Highest Missing Values:
EmployeeID
Missing Value Count:
0
Number of Duplicate Records: 0
Dataset Size Before Cleaning: 10
Dataset Size After Cleaning: 10